const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
        ShadingType, LevelFormat, PageBreak, PageNumber } = require("docx");
const fs = require("fs");

// ─── Read input JSON from stdin ───
let inputData = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", chunk => inputData += chunk);
process.stdin.on("end", async () => {
    try {
        const data = JSON.parse(inputData);
        const buffer = await generateDocument(data);
        fs.writeFileSync(data.output_path, buffer);
        process.stdout.write(JSON.stringify({ success: true, path: data.output_path }));
    } catch (err) {
        process.stderr.write(err.message + "\n" + err.stack);
        process.exit(1);
    }
});


async function generateDocument(data) {
    const { file_name, doc_type, processed_at, raw_sections, structured_sections } = data;

    const docTypeTitles = {
        invoice: "Invoice",
        contract: "Contract",
        crac: "CRAC Document",
    };
    const docTypeColors = {
        invoice: "E8590C",
        contract: "4F46E5",
        crac: "0891B2",
    };

    const title = docTypeTitles[doc_type] || "Document";
    const accentColor = docTypeColors[doc_type] || "4F46E5";

    // ─── Build children ───
    const children = [];

    // ── Cover / Title ──
    children.push(new Paragraph({
        spacing: { after: 80 },
        children: [
            new TextRun({ text: title.toUpperCase(), font: "Arial", size: 36, bold: true, color: accentColor }),
        ],
    }));

    children.push(new Paragraph({
        spacing: { after: 40 },
        children: [
            new TextRun({ text: "OCR Extraction Report", font: "Arial", size: 22, color: "6B7280" }),
        ],
    }));

    // ── Meta info table ──
    const metaBorder = { style: BorderStyle.NONE, size: 0 };
    const metaBorders = { top: metaBorder, bottom: metaBorder, left: metaBorder, right: metaBorder };

    const metaItems = [
        ["Source File", file_name || "Unknown"],
        ["Document Type", (doc_type || "").toUpperCase()],
        ["Processed At", (processed_at || "").slice(0, 19).replace("T", " ")],
    ];

    children.push(new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [2400, 6960],
        rows: metaItems.map(([label, value]) =>
            new TableRow({
                children: [
                    new TableCell({
                        borders: metaBorders,
                        width: { size: 2400, type: WidthType.DXA },
                        margins: { top: 40, bottom: 40, left: 0, right: 80 },
                        children: [new Paragraph({
                            children: [new TextRun({ text: label, font: "Arial", size: 18, bold: true, color: "374151" })]
                        })],
                    }),
                    new TableCell({
                        borders: metaBorders,
                        width: { size: 6960, type: WidthType.DXA },
                        margins: { top: 40, bottom: 40, left: 80, right: 0 },
                        children: [new Paragraph({
                            children: [new TextRun({ text: value, font: "Arial", size: 18, color: "1F2937" })]
                        })],
                    }),
                ],
            })
        ),
    }));

    children.push(new Paragraph({ spacing: { before: 200, after: 200 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: accentColor, space: 1 } },
        children: [],
    }));

    // ── Structured Data Section ──
    if (structured_sections && structured_sections.length > 0) {
        renderSections(children, structured_sections, accentColor);

        children.push(new Paragraph({ spacing: { before: 200, after: 200 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: "E5E7EB", space: 1 } },
            children: [],
        }));
    }

    // ── Raw Text Section ──
    if (raw_sections && raw_sections.length > 0) {
        children.push(new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 300, after: 160 },
            children: [new TextRun({ text: "Full Extracted Text", font: "Arial", size: 28, bold: true, color: "1F2937" })],
        }));

        renderSections(children, raw_sections, accentColor);
    }

    // ── Footer note ──
    children.push(new Paragraph({ spacing: { before: 400 }, children: [] }));
    children.push(new Paragraph({
        spacing: { before: 100 },
        children: [
            new TextRun({ text: "Generated by DocVision OCR • Powered by Mistral Vision via Ollama",
                          font: "Arial", size: 16, italics: true, color: "9CA3AF" }),
        ],
    }));


    const doc = new Document({
        styles: {
            default: {
                document: {
                    run: { font: "Arial", size: 22 },
                },
            },
            paragraphStyles: [
                {
                    id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
                    run: { size: 28, bold: true, font: "Arial", color: "1F2937" },
                    paragraph: { spacing: { before: 280, after: 160 }, outlineLevel: 0 },
                },
                {
                    id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
                    run: { size: 24, bold: true, font: "Arial", color: "374151" },
                    paragraph: { spacing: { before: 200, after: 120 }, outlineLevel: 1 },
                },
            ],
        },
        numbering: {
            config: [
                {
                    reference: "bullets",
                    levels: [{
                        level: 0, format: LevelFormat.BULLET, text: "\u2022",
                        alignment: AlignmentType.LEFT,
                        style: { paragraph: { indent: { left: 720, hanging: 360 } } },
                    }],
                },
                {
                    reference: "numbers",
                    levels: [{
                        level: 0, format: LevelFormat.DECIMAL, text: "%1.",
                        alignment: AlignmentType.LEFT,
                        style: { paragraph: { indent: { left: 720, hanging: 360 } } },
                    }],
                },
            ],
        },
        sections: [{
            properties: {
                page: {
                    size: { width: 12240, height: 15840 },
                    margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
                },
            },
            headers: {
                default: new Header({
                    children: [new Paragraph({
                        alignment: AlignmentType.RIGHT,
                        children: [new TextRun({ text: `DocVision OCR — ${title}`, font: "Arial", size: 16, color: "9CA3AF", italics: true })],
                    })],
                }),
            },
            footers: {
                default: new Footer({
                    children: [new Paragraph({
                        alignment: AlignmentType.CENTER,
                        children: [
                            new TextRun({ text: "Page ", font: "Arial", size: 16, color: "9CA3AF" }),
                            new TextRun({ children: [PageNumber.CURRENT], font: "Arial", size: 16, color: "9CA3AF" }),
                        ],
                    })],
                }),
            },
            children: children,
        }],
    });

    return await Packer.toBuffer(doc);
}


function renderSections(children, sections, accentColor) {
    const border = { style: BorderStyle.SINGLE, size: 1, color: "D1D5DB" };
    const borders = { top: border, bottom: border, left: border, right: border };

    const headerShadingColors = {
        "E8590C": "FEF3E8",  // invoice: light orange
        "4F46E5": "EEF0FB",  // contract: light indigo
        "0891B2": "E8F8FB",  // crac: light cyan
    };
    const headerShading = headerShadingColors[accentColor] || "F3F4F6";

    for (const section of sections) {
        switch (section.type) {
            case "heading":
                children.push(new Paragraph({
                    heading: section.level === 1 ? HeadingLevel.HEADING_1 : HeadingLevel.HEADING_2,
                    spacing: { before: section.level === 1 ? 280 : 200, after: section.level === 1 ? 160 : 120 },
                    children: [new TextRun({
                        text: section.text,
                        font: "Arial",
                        size: section.level === 1 ? 28 : 24,
                        bold: true,
                        color: section.level === 1 ? "1F2937" : "374151",
                    })],
                }));
                break;

            case "key_value":
                children.push(new Table({
                    width: { size: 9360, type: WidthType.DXA },
                    columnWidths: [3200, 6160],
                    rows: [new TableRow({
                        children: [
                            new TableCell({
                                borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.SINGLE, size: 1, color: "F3F4F6" },
                                           left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
                                width: { size: 3200, type: WidthType.DXA },
                                shading: { fill: "F9FAFB", type: ShadingType.CLEAR },
                                margins: { top: 60, bottom: 60, left: 120, right: 80 },
                                children: [new Paragraph({
                                    children: [new TextRun({ text: section.label || "", font: "Arial", size: 20, bold: true, color: "4B5563" })],
                                })],
                            }),
                            new TableCell({
                                borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.SINGLE, size: 1, color: "F3F4F6" },
                                           left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
                                width: { size: 6160, type: WidthType.DXA },
                                margins: { top: 60, bottom: 60, left: 120, right: 120 },
                                children: [new Paragraph({
                                    children: [new TextRun({ text: section.value || "", font: "Arial", size: 20, color: "1F2937" })],
                                })],
                            }),
                        ],
                    })],
                }));
                break;

            case "table":
                if (section.data && section.data.length > 0) {
                    const headers = Object.keys(section.data[0]);
                    const colCount = headers.length;
                    const colWidth = Math.floor(9360 / colCount);
                    const colWidths = headers.map(() => colWidth);

                    const headerRow = new TableRow({
                        tableHeader: true,
                        children: headers.map(h => new TableCell({
                            borders, width: { size: colWidth, type: WidthType.DXA },
                            shading: { fill: headerShading, type: ShadingType.CLEAR },
                            margins: { top: 60, bottom: 60, left: 80, right: 80 },
                            children: [new Paragraph({
                                children: [new TextRun({ text: h.replace(/_/g, " ").toUpperCase(), font: "Arial", size: 16, bold: true, color: "374151" })],
                            })],
                        })),
                    });

                    const dataRows = section.data.map(row => new TableRow({
                        children: headers.map(h => new TableCell({
                            borders, width: { size: colWidth, type: WidthType.DXA },
                            margins: { top: 50, bottom: 50, left: 80, right: 80 },
                            children: [new Paragraph({
                                children: [new TextRun({ text: String(row[h] ?? ""), font: "Arial", size: 18, color: "1F2937" })],
                            })],
                        })),
                    }));

                    children.push(new Table({
                        width: { size: 9360, type: WidthType.DXA },
                        columnWidths: colWidths,
                        rows: [headerRow, ...dataRows],
                    }));
                }
                break;

            case "list_item":
                children.push(new Paragraph({
                    numbering: { reference: "bullets", level: 0 },
                    spacing: { before: 40, after: 40 },
                    children: [new TextRun({ text: section.text, font: "Arial", size: 20, color: "1F2937" })],
                }));
                break;

            case "numbered_item":
                children.push(new Paragraph({
                    numbering: { reference: "numbers", level: 0 },
                    spacing: { before: 40, after: 40 },
                    children: [new TextRun({ text: section.text.replace(/^\d+[\.\)]\s*/, ""), font: "Arial", size: 20, color: "1F2937" })],
                }));
                break;

            case "paragraph":
            default:
                if (section.text && section.text.trim()) {
                    children.push(new Paragraph({
                        spacing: { before: 60, after: 60 },
                        children: [new TextRun({ text: section.text, font: "Arial", size: 20, color: "1F2937" })],
                    }));
                }
                break;
        }
    }
}